--h2 database
--drop table if exists member CASCADE;
--create table member
--(
--    id bigint generated by default as identity,
--    name varchar(255),
--    primary key (id)
--);

-- mysql
create table member
(
    id int not null auto_increment primary key,
    name varchar(255)
);